export default derive = [
  "ça rit",
  "comme avant les dimanches",
  "au loin les clochers",
  "et les draps qui claquent",
  "tout près des fleurs sauvages",
  "mais ici",
  "sans draps",
  "sans corde à linge",
  "sans bosquets",
  "les églises enchevêtrées aux grues",
  "qui tissent à tour de bras",
  "des pièces vides",
  "ça rit",
  "ça rit comme ça recommence",
  "comme les jambes qui s’acharnent encore contre la ville",
  "à bout de lumière et de béton",
  "même si plus personne ne nous porte sur ses épaules",
  "pour traverser la rue",
  "comme avant la rivière qui nous donnait un nom"
]
