/*
            SIGNIFICATION SIGLES
V : verbe | G : groupe de mots | N : nom | A : adverbes
A : aléatoire | G : GPS | V : vitesse : | T : température | S :saison
*/

export default derive_matin = [
    "Partout",
    "l’air $V00A",
    "dans tes pas",
    "$N00G $V00A",
    "pousse en deux",
    "en mille",
    "et plante",
    "ses $N01A d'oiseaux",
    "\n",
    "$N02S a ton allure",
    "\n",
    "Tu $V01A",
    "la $N03T",
    "Tu $V01A",
    "la rosée",
    "sur $N04A des $N05G",
    "et le temps",
    "$V02V",
    "le long des cimes $G00G",
    "Partout",
    "le $N06A",
    "levant",
    "Partout",
    "le matin",
    "en $N07A",
    "dans la $A00A des $N08G",
    "\n",
    "Le $N09A $V03V",
    "$A01A du jour",
    "devant",
    "le jour",
    "par $N10A",
    "qui $V04A",
    "Les $N11G s’éclairent",
    "Les ombres $V05A",
    "et se taisent",
    "\n",
    "$A02V",
    "la $N03T",
    "$V06V",
    "$V07A",
    "dans tes $N12A",
    "\n",
    "Tu $V08V",
    "Tu viens",
    "\n",
]
