/*
            SIGNIFICATION SIGLES
V : verbe | G : groupe de mots | N : nom | A : adverbes
A : aléatoire | G : GPS | V : vitesse : | T : température | S :saison
*/

export default derive_soir = [
  "Déjà",
  "le soir $V17A",
  "$G02A",
  "Tu vas",
  "Tu $V08V",
  "comme s$G03A",
  "$G04A",
  "$V18A les $N01A",
  "$G05A des $N21A",
  "$V19A",
  "\n",
  "Toi,",
  "$N22A en $N23A",
  "Tu $V20V la $N03T",
  "qui passe",
  "Tu $V20V",
  "sans $V21V",
  "sans savoir si",
  "l$N00G $V22A",
  "à $N24V",
  "Ou si c’est toi",
  "sur elle",
  "Qui $V23A l’autre ?",
  "Qui $V24A?",
  "\n",
  "Tu $V20V",
  "$A03V",
  "dans les bruits",
  "de tout ce qui $V25V,",
  "$N25A et $N11G",
  "de tout ce qui $V26A",
  "avec nous",
  "$G06S",
  "tout ce qu’on $V27A",
  "sous ce qui vient",
  "Tu $V08V",
  "$G07A l$N26A",
  "des $N27A",
  "\n",
  "Tu $V28V",
  "\n",
  "Tu saisis",
  "comme l’ombre",
  "$V29A la nuit",
]
