export default derive_midi = [
    "Autre moment",
    "La %ENDROIT[GPS] mal fermée",
    "%V ses %N",
    "comme des odeurs",
    "de pain,",
    "de %FRUIT[SAISON]",
    "et de %FLEUR[SAISON]",
    "De %ENDROIT[VITESSE] en %ENDROIT[VITESSE]",
    "Tout ce qui %V[VITESSE] au bord de toi",
    "Tout ce qui te %V[VITESSE]",
    "Le jour t’apprend,",
    "%V tes traces",
    "et fredonne tes visages",
    "Le souvenir",
    "dans la grossesse de l’automne",
    "s’éteint",
    "La mère s’apaise",
    "Les pins sèchent",
    "Les champs reposent",
    "Ton corps s’augmente",
    "à taille de pays",
    "Tu es là",
    "où s’abritent les mondes"
  ]
