export default derive_soir = [
  "Déjà",
  "le jour se penche",
  "dans ton dos",
  "Tu vas",
  "Tu avances",
  "comme se secoue la nappe",
  "après le vin du dimanche",
  "s’empochent les silences",
  "aux mains des statues",
  "perdurent",
  "Toi",
  "Les yeux en avenue",
  "Tu prends le vent",
  "qui passe",
  "Tu prends",
  "sans te retourner",
  "sans savoir si",
  "la ville s’imprime",
  "sur tes talons",
  "Ou si c’est toi",
  "sur elle",
  "Qui emprunte l’autre ?",
  "Qui pèse ?",
  "Tu prends",
  "bruissant",
  "dans les bruits",
  "de tout ce qui s’acharne,",
  "gyrophares et grues",
  "de tout ce qui s’est dressé",
  "avec nous",
  "dans le soleil",
  "tout ce qu’on raconte",
  "sous ce qui vient",
  "Tu avances",
  "Tes âges ont l’insolence",
  "des torches",
  "Tu prolonges",
  "Tu saisis",
  "comme l’ombre",
  "amorce la nuit"
]
