export default derive_nuit = [
  "La nuit par-dessus les herbes",
  "Irrévocable",
  "par-dessus tes épaules",
  "La nuit",
  "pleine de forêt",
  "vient",
  "tapisse nos chemins",
  "te déchausse",
  "Tu persistes",
  "Au milieu",
  "s’ouvre l’œil",
  "énorme",
  "de tous les boisements",
  "de la nuit",
  "un œil impossible à fermer",
  "qui te regarde",
  "les cils mêlés aux arbres",
  "La nuit te rattrape",
  "Elle te happe",
  "dans cet œil où",
  "des royaumes bougent",
  "les traces des peuples",
  "bâtis comme des légendes",
  "tous les mondes tentés",
  "dans cet œil",
  "qui voit",
  "La nuit te rattrape",
  "Elle dénude",
  "Les bois frémissent",
  "Et dans le regard épais",
  "des ombres de labour",
  "en face",
  "l’œil de la nuit",
  "au plus loin de toi,",
  "l’œil te rencontre",
  "La nuit",
  "te rattrape"
]
