/* === Helpers contenant la base de mots, en format json === */

export default base_de_mots = {
  V : [
    ["s'ouvre", "tremble", "perce", "éclate", "s'étend", "gronde", "s'étire", "s'avance"],
    ["endosses", "chausses", "franchis"],
    {stationary : ["flâneur"], walking : ["battant"], running : ["chahutant"], cycling : ["dévalant"], in_vehicle : ["floutant"]},
    {stationary : ["crépite"], walking : ["remue", "bouge"], running : ["s'ébroue"], cycling : ["défile"], in_vehicle : ["disparaît"]},
    ["croît", "s'entête", "persiste"],
    ["tiédissent", "sourient", "valsent"],
    {stationary : ["monte"], walking : ["grimpe", "te rencontre"], running : ["se soulève", "t'affleure"], cycling : ["te fouette"], in_vehicle : ["te transperce"]},
    ["s'enfonce", "résonne", "exulte"],
    {stationary : ["es immobile"], walking : ["marches"], running : ["cours"], cycling : ["roules"], in_vehicle : ["fuses"]},
    {stationary : ["t'apprend"], walking : ["te ressemble"], running : ["te sait"], cycling : ["te devinne"], in_vehicle : ["t'oublie"]},
    ["vendange", "emprunte", "amasse"],
    {stationary : ["fredonne"], walking : ["scande"], running : ["clame"], cycling : ["crie"], in_vehicle : ["hurle"]},
    ["s'éteint", "s'abolit", "s'oublie", "se range"],
    ["sèchent", "endurent", "soutiennent"],
    ["s'augmente", "pèse", "se peuple", "s'ouvre"],
    ["s'abritent", "veillent", "grandissent", "résistent"],
    ["répand", "tisse", "écume"],
  ],
  N : [
    {rural : ["Le chemin", "La terre", "La campagne"], urbain : ["La ville", "La route", "Le trottoir", "La chaussée"]},
    ["rumeurs", "nuées", "légendes", "histoires"],
    {printemps : ["le printemps"], automne : ["l'automne"], hiver : ["l'hiver"], été : ["l'été"]},
    {cold : ["fraîcheur"], sweet : ["douceur"], hot : ["chaleur"]}, // à modifier selon weather_description
    ["la fatigue", "le silence", "le sommeil"],
    {rural : ["bêtes"], urbain : ["pierres"]},
    ["monde", "chant", "pays"],
    ["murmure", "chantier"],
    {rural : ["herbes"], urbain : ["rues"]},
    ["sol", "ciel"],
    ["les racines", "la graine"],
    {rural : ["arbres", "champs"], urbain : ["toits", "ponts", "grues"]},
    ["mains", "jambes"],
    {printemps : ["de fraises", "de cerises", "de prunes", "de pêches", "d'abricots", "d'avocats", "de bananes"], automne : ["de pommes", "de poires", "de coings"], hiver : ["d'oranges", "de clémentines", "de mandarines"], été : ["de melons", "de pastèques", "de framboises", "de figues"]},
    {printemps : ["de jonquilles", "de muguet", "de jacinthes"], automne : ["de camélias", "de sauge", "de feuilles mortes", "de mousse"], hiver : ["de perce-neige", "d'iris", "de pensées"], été : ["de dahlias", "de roses", "de geraniums", "d'œillets", "de pétunias"]},
    {stationary : ["secondes"], walking : ["pas"], running : ["rues"], cycling : ["rues"], in_vehicle : ["villes"]},
    ["visages", "noms", "traits"],
    {stationary : ["L'errance"], walking : ["Le souvenir"], running : ["La guerre"], cycling : ["La course"], in_vehicle : ["Le voyage"]},
    ["taille", "mesure", "hauteur"],
    ["de pays", "du midi"],
    ["mondes", "temps"],
  ],
  G : [
    {rural : ["de blé"], urbain : ["d'acier"]},
    ["La mère s'apaise", "Le père se tait"],
  ],
  A : [
    ["rousseur", "clameur"],
    ["plein", "ébahi", "au bord"],
    {stationary : ["très lentement"], walking : ["lentement"], running : ["soudainement"], cycling : ["brusquement"], in_vehicle : ["succintement"]},
  ],
}
